#!/bin/bash

NAME="exploratorium"                                            # Name of the application
DJANGODIR=/home/ubuntu/exploratorium/backend                    # Django project directory
SOCKFILE=/home/ubuntu/run/exploratorium_gunicorn.sock 	                # we will communicate using this unix socket
LOGFILE=/home/ubuntu/run/logs/exploratorium_gunicorn_supervisor.log
NUM_WORKERS=4                                               # how many worker processes should Gunicorn spawn
DJANGO_WSGI_MODULE=config.wsgi                              # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/ubuntu/exploratorium/venv/bin/activate

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
chmod 777 $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--log-level=warning \
--log-file=$LOGFILE \
--bind=unix:$SOCKFILE
# --bind 0:80  # run directly without nginx for testing
